### PR TITLE
Add quiet option

### PR DESCRIPTION
**Pull request by juzim**
We share the punch config across multiple projects where some files might not exists.

### CODE REVIEW

**Comment by lgiordani** [comment]
Thanks! I have to sort out the issue with the tests (see the Travis build) and then it's fine. I'm working on punch (even though it seems nothing is changing), but I will merge and release this as soon as possible

**Comment by lgiordani** [comment]
Can you please merge develop? I want to check if all test pass now, I updated the test suite to pytest 4

**Comment by juzim** [comment]
Done, looks good.

**Comment by lgiordani** [comment]
Thanks! I'll release this soon (promise) together with some other behind-the-scenes improvements that will ease the introduction of some bigger changes

**Pull request merged**
